### ISSUE TITLE
Secure Application by Storing Sensitive Details in Environment Variables 

### ISSUE THREAD

**Issue by Anjali0407-git** [oss-slu/material-donor-mutual-assist#3]
Currently, our application stores sensitive details such as database credentials and AWS access keys directly in the source code. This practice poses a security risk, exposing sensitive data to potential leaks. To enhance security, we need to move all sensitive configuration details into an environment variable file (.env) and ensure it is excluded from version control by adding it to .gitignore.

Task:
- Create distinct .env files for the client-app, admin-module, and email-module to store their specific sensitive configurations.
- Modify the application configuration to load these details from the .env file using a package like dotenv.
- Update .gitignore to include the .env file to prevent it from being tracked by Git.

**Comment by milan567** [comment]
Hi @Anjali0407-git   I would like to help you on this project by resolving this issue. If you are ok with it you can assign me the issue.

**Comment by Anjali0407-git** [comment]
@milan567 Good first issues have all been assigned to other students in the last sprint.
You can explore other latest tasks at here https://github.com/orgs/oss-slu/projects/41/views/1 and you can work on any of them. Make sure to move them to In Progress or else notify me before starting working on any of those issues. Thank you!
