### ISSUE TITLE
Enhance Clickable Area and Hover Responsiveness in Donations Table

### ISSUE THREAD

**Issue by Anjali0407-git** [oss-slu/material-donor-mutual-assist#76]
To improve the usability of the /donations page, we propose making the entire table cell clickable, not just the donation ID, and adding responsiveness on hover.

![image](https://github.com/user-attachments/assets/07d9cf5d-d325-4c56-ad91-4aba1e19355b)

Responsibilities:

- Clickable Table Cells: Extend the clickable area from just the donation ID to the entire table cell corresponding to each donation. This change should apply to cells that lead to specific donor detail pages.
- Hover Responsiveness: Implement a hover effect for the clickable cells to indicate to users that they are interactive. This could include a slight color change or underlining text to visually signify the cell's functionality.

**Comment by Gayatrinj** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?
