### ISSUE TITLE
Implement Signup UI and Functionality

### ISSUE THREAD

**Issue by Anjali0407-git** [oss-slu/material-donor-mutual-assist#80]
Develop the user interface for the signup page along with its functionality. This includes designing the UI, integrating it with the website, handling form validations, submissions, interactions with the backend API, and performing unit tests.

**Tasks:**

- Design and create responsive design for the signup page.
- Integrate the signup UI into the existing website.
- Implement frontend validations for email, password criteria, confirm password, and required fields.
- Handle form submissions with appropriate feedback mechanisms.
- Conduct unit tests for all frontend validation logic and form handling.

**Comment by M-Ravali** [comment]
Hi, I would like to contribute to this project. I would appreciate it if you could assign this issue to me.

**Comment by smridhiu** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by Anjali0407-git** [comment]
@M-Ravali this issue along with Login functionality has been addressed by other team mate in [this PR ](https://github.com/oss-slu/material-donor-mutual-assist/pull/89)

I need to close this issue now. Please let me know if you want to work on other available frontend issues, thank you.
